resources:
  - name: my_source_repo
    type: GitRepo
    configuration:
      gitProvider: sriman
      path: srimanpadmanaban/springtest
      branches:
        include: master
        
pipelines:
  - name: pipeline_affinityGroup_example
    configuration:
      inputResources:
        - name: my_source_repo
      environmentVariables:
        readOnly:
          MY_DIR: "/tmpdir"
    steps:
      - name: ag_step_1
        type: Bash
        configuration:
          affinityGroup: together
        execution:
          onExecute:
            - mkdir $MY_DIR
            - echo "Running " $pipeline_name "|" $step_name >$MY_DIR/myoutput.txt
            - cat $MY_DIR/myoutput.txt
