apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy

on:
  push:
    branches:
      - "**"
      
jobs:
  build-publish:
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1
