name: Hello World Workflow

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every day at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World from Build
        run: |
          echo "Hello, World from Build!"
          sleep 10

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World from Test
        run: | 
          echo "Hello, World from Test!"
          sleep 15

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World from Deploy
        run: |
          echo "Hello, World from Deploy!"
          sleep 10

        
